config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :users, :controller => "users"
  resources :desempenhos
  resources :orgaos
  resources :magistrados
  resources :desembargadores

  get 'desempenho_vazio' => 'desempenhos#desempenho_vazio'
  get 'listar_desempenhos' => 'desempenhos#listar_desempenhos'
  get 'desempenhos_magistrados' => 'desempenhos#desempenhos_magistrados'
  get 'desempenhos_orgaos' => 'desempenhos#desempenhos_orgaos'
  post 'gerar_desempenho' => 'desempenhos#gerar_desempenho'
  post 'bloquear/:id' => 'desempenhos#bloquear', as: 'bloquear'
  post 'desbloquear/:id' => 'desempenhos#desbloquear', as: 'desbloquear'
  root to: 'desempenhos#index'

end








app/models/desempenho.rb
class Desempenho < ApplicationRecord
  belongs_to :orgao
  belongs_to :magistrado
  belongs_to :user
  # before_save :calcular_residuos
  before_create :setData, on: :create
  validates_presence_of :decisoes, :decisoes_557, :acordos_homologados, :julgamentos_com_merito, :julgamentos_sem_merito, :distribuidos, :redistribuidos, :magistrado_id, :orgao_id, message: "Campo obrigatório."
  validates_numericality_of :decisoes, :decisoes_557, :acordos_homologados, :julgamentos_com_merito, :julgamentos_sem_merito, :distribuidos, :redistribuidos, :greater_than_or_equal_to => 0, message: "Valor deve ser maior que zero."
  validate :validate_magistrado_have_orgao
  validate :validate_user_have_orgao
  # validate :validate_saldo_residuo
  # validate :validate_creation_date, on: :create
  # validate :validate_uniqueness, on: :create
  validate :validar_pendencias, on: :save

  def self.search(search)
    if search
      where(:data => Time.new(2017, search))
    else
      all
    end
  end

  protected

  def calcular_residuos
    julgamentosComMerito = self.julgamentos_com_merito
    julgamentosSemMerito = self.julgamentos_sem_merito
    acordosHomologados = self.acordos_homologados
    distribuidos = self.distribuidos
    self.residuos = distribuidos - (julgamentosComMerito + julgamentosSemMerito + acordosHomologados)
  end

  def setData
    unless self.data?
      time = Time.now - 1.month
      self.data = Time.new(time.year, time.month)
    else
      self.ativo = false
    end
  end

  private

  def validate_magistrado_have_orgao
    magistrado = Magistrado.where(:id => self.magistrado_id).joins(:orgaos).where(:orgaos => {:id => self.orgao})
    errors.add(:orgao_id, 'Orgão não pertecente a este magistrado.') unless magistrado.exists?
  end

  def validate_creation_date
      errors.add(:orgao_id, 'Data disponivel para lançamentos apenas entre os dias 1-15.') unless Time.now.strftime("%d").to_i <= 15
  end

  def validate_uniqueness
    time = Time.now - 1.month
    time = Time.new(time.year, time.month)
    desempenho = Desempenho.where(:data => time).joins(:orgao).where(:orgaos => {:id => self.orgao}).joins(:magistrado).where(:magistrados => {:id => self.magistrado})
    errors.add(:orgao_id, 'Lançamento já realizado.') if desempenho.exists?
  end

  def validate_user_have_orgao
    user = User.where(:id => self.user_id).joins(:orgaos).where(:orgaos => {:id => self.orgao})
    errors.add(:orgao_id, 'Você não tem acesso a este orgão') unless user.exists?
  end

  def validate_saldo_residuo
    julgamentosComMerito = self.julgamentos_com_merito
    julgamentosSemMerito = self.julgamentos_sem_merito
    acordosHomologados = self.acordos_homologados
    distribuidos = self.distribuidos
    residuoAtual =  distribuidos - (julgamentosComMerito + julgamentosSemMerito + acordosHomologados)
    residuoAnterior = Desempenho.all.where.not(:id => self.id, :ativo => false).joins(:orgao, :magistrado).where({:magistrados => {:id => self.magistrado_id}}).where({:orgaos => {:id => self.orgao_id}}).sum(:residuos)
    residuo = (residuoAtual + residuoAnterior)
    return self.errors.add(:base, "Valor Incompativel!") if residuo < 0
  end

  def validar_pendencias
    desempenhos = Desempenho.all.where(:ativo => true).joins(:orgao, :magistrado).where({:magistrados => {:id => self.magistrado_id}}).where({:orgaos => {:id => self.orgao_id}})
    return self.errors.add(:base, "Existem Desempenhos Pendentes a serem editados") if desempenhos.exists? && self.ativo != true
  end
end

app/controllers/desempenhos_controller.rb
class DesempenhosController < ApplicationController
  load_and_authorize_resource
  before_action :set_desempenho, only: [:edit, :show, :update, :destroy]

  def index
    @desempenhos = Desempenho.where(ativo: true).group(:data)
    @grafico = Desempenho.where(ativo: true).group(:data).sum(:residuos)
  end

  def desempenho_vazio
    redirect_to desempenhos_path, notice: 'Acesso negado' unless current_user.role === 'admin'
    @desempenho = Desempenho.new
  end

  def gerar_desempenho
    redirect_to desempenhos_path, notice: 'Acesso negado' unless current_user.role === 'admin'
    @desempenho = Desempenho.new(desempenho_params)
    @desempenho.user_id = current_user.id if current_user
    @desempenho.decisoes = 0
    @desempenho.decisoes_557 = 0
    @desempenho.acordos_homologados = 0
    @desempenho.julgamentos_com_merito = 0
    @desempenho.julgamentos_sem_merito = 0
    @desempenho.distribuidos = 0
    @desempenho.redistribuidos = 0
    @desempenho.ativo = false
    if @desempenho.save!
      redirect_to desempenhos_path, notice: 'Desempenho Criado Com Sucesso.'
    else
      render :desempenho_vazio
    end
  end

  def listar_desempenhos
    @desempenhos = Desempenho.all
  end

  def desempenhos_magistrados
    @desempenhos = Desempenho.search(params[:mes]).group_by(&:magistrado)
    @grafico = Magistrado.all.map {|magistrado| {
      name: magistrado.name,
      data: magistrado.desempenhos.where(ativo: true).group(:data).sum(:residuos)
    }}
  end

  def desempenhos_orgaos
    @desempenhos = Desempenho.search(params[:mes]).group_by(&:orgao)
    @grafico = Orgao.all.map {|orgao| {
      name: orgao.name,
      data: orgao.desempenhos.where(ativo: true).group(:data).sum(:residuos)
    }}
  end

  def show
  end

  def new
    @desempenho = Desempenho.new
  end

  def edit
  end

  def create
    @desempenho = Desempenho.new(desempenho_params)
    @desempenho.user_id = current_user.id if current_user
    if @desempenho.save
      redirect_to desempenhos_url, notice: 'Desempenho criado com sucesso.'
    else
      render :new
    end
  end

  def update
      if @desempenho.update(desempenho_params)
        redirect_to desempenhos_url, notice: 'Desempenho editado com sucesso.'
      else
        render :edit
      end
  end

  def bloquear
    Desempenho.update((params[:id]), :ativo => true)
  end
  helper_method :bloquear

  def desbloquear
    Desempenho.update((params[:id]), :ativo => false)
  end
  helper_method :desbloquear

  def destroy
    @desempenho.destroy
    redirect_to desempenhos_url, notice: 'Desempenho destruido com sucesso.'
  end

  private

  def set_desempenho
    @desempenho = Desempenho.find(params[:id])
  end

  def desempenho_params
    params.require(:desempenho).permit(:user_id, :orgao_id, :magistrado_id, :decisoes, :decisoes_557, :acordos_homologados, :julgamentos_com_merito, :julgamentos_sem_merito, :distribuidos, :redistribuidos, :residuos, :ativo, :mes, :data)
  end
end

app/helpers/desempenhos_helper.rb
module DesempenhosHelper
end

app/views/desempenhos/_form.html.erb
<%= simple_form_for(@desempenho) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :orgao, as: :select, include_blank: false %>
    <%= f.association :magistrado, as: :select, include_blank: false %>
    <%= f.input :decisoes %>
    <%= f.input :decisoes_557 %>
    <%= f.input :acordos_homologados %>
    <%= f.input :julgamentos_com_merito %>
    <%= f.input :julgamentos_sem_merito %>
    <%= f.input :distribuidos %>
    <%= f.input :redistribuidos %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/desempenhos/desempenho_vazio.html.erb
<div class="page-header">
  <h1>Gerar Desempenho</h1>
</div>
<div class="container">
  <%= simple_form_for @desempenho, :url => gerar_desempenho_path, :method => :post do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <label for="">Data Referente</label>
      <%= f.date_select :data, {start_year: 2017, end_year: Time.now.year, :discard_day => true}, {:class => "form-control"} %>
      <%= f.association :orgao, as: :select, include_blank: false %>
      <%= f.association :magistrado, as: :select, include_blank: false %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, {class: "btn btn-sm btn-primary"} %>
    </div>
  <% end %>
</div>


app/views/desempenhos/desempenhos_magistrados.html.erb
<div class="container">
    <div class="page-header">
        <h1>Desempenhos Magistrados</h1>
    </div>
    <%= form_tag desempenhos_magistrados_path, class: "form-inline", :method => 'get' do %>
        <div class="input-group-row col-sm-2">
        <label for="mes" class="sr-only">Selecione o Mês</label>
        <%= select_tag(:mes,
            options_for_select([
                ['Janeiro', 1],
                ['Fevereiro', 2],
                ['Março', 3],
                ['Abril', 4],
                ['Maio', 5],
                ['Junho', 6],
                ['Julho', 7],
                ['Agosto', 8],
                ['Setembro', 9],
                ['Outubro', 10],
                ['Novembro', 11],
                ['Dezembro', 12]
                ]),
        {class: "form-control", name: "mes"}) %>
        </div>
        <div class="btn-group" role="group">
            <%= submit_tag "Filtrar", :name => nil, class: "btn btn-primary" %>
            <% if params[:mes] %>
                <%= link_to "Limpar Filtro", desempenhos_magistrados_path, class: "btn btn-warning" %>
            <% end %>
        </div>
    <% end %>
    <% if @desempenhos %>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Magistrado</th>
                    <th>Decisoes</th>
                    <th>Decisoes 557</th>
                    <th>acordos_homologados</th>
                    <th>Julgamentos Com Mérito</th>
                    <th>Julgamentos Sem Mérito</th>
                    <th>distribuidos</th>
                    <th>Redistribuidos</th>
                    <th>Residuos</th>
                </tr>
            </thead>
            <tbody>
                <% @desempenhos.each do |magistrado, desempenhos| %>
                    <tr>
                        <td> <%= magistrado.name %> </td>
                        <td> <%= desempenhos.sum(&:decisoes) %> </td>
                        <td> <%= desempenhos.sum(&:decisoes_557) %> </td>
                        <td> <%= desempenhos.sum(&:acordos_homologados) %> </td>
                        <td> <%= desempenhos.sum(&:julgamentos_com_merito) %> </td>
                        <td> <%= desempenhos.sum(&:julgamentos_sem_merito) %> </td>
                        <td> <%= desempenhos.sum(&:distribuidos) %> </td>
                        <td> <%= desempenhos.sum(&:redistribuidos) %> </td>
                        <td> <%= desempenhos.sum(&:residuos) %> </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= column_chart @grafico %>
    <% else %>
        <h2>Nenhum Desempenho Nesse Periodo</h2>
    <% end %>
</div>

app/views/desempenhos/desempenhos_orgaos.html.erb
<div class="container">
    <div class="page-header">
        <h1>Desempenhos Orgãos</h1>
    </div>
    <%= form_tag desempenhos_orgaos_path, class: "form-inline", :method => 'get' do %>
        <div class="input-group-row col-sm-2">
        <label for="mes" class="sr-only">Selecione o Mês</label>
        <%= select_tag(:mes,
            options_for_select([
                ['Janeiro', 1],
                ['Fevereiro', 2],
                ['Março', 3],
                ['Abril', 4],
                ['Maio', 5],
                ['Junho', 6],
                ['Julho', 7],
                ['Agosto', 8],
                ['Setembro', 9],
                ['Outubro', 10],
                ['Novembro', 11],
                ['Dezembro', 12]
                ]),
        {class: "form-control", name: "mes"}) %>
        </div>
        <div class="btn-group" role="group">
            <%= submit_tag "Filtrar", :name => nil, class: "btn btn-primary" %>
            <% if params[:mes] %>
                <%= link_to "Limpar Filtro", desempenhos_orgaos_path, class: "btn btn-warning" %>
            <% end %>
        </div>
    <% end %>
    <% if @desempenhos %>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Orgão</th>
                    <th>Decisoes</th>
                    <th>Decisoes 557</th>
                    <th>acordos_homologados</th>
                    <th>Julgamentos Com Mérito</th>
                    <th>Julgamentos Sem Mérito</th>
                    <th>distribuidos</th>
                    <th>Redistribuidos</th>
                    <th>Residuos</th>
                </tr>
            </thead>
            <tbody>
                <% @desempenhos.each do |orgao, desempenhos| %>
                    <tr>
                        <td> <%= orgao.name %> </td>
                        <td> <%= desempenhos.sum(&:decisoes) %> </td>
                        <td> <%= desempenhos.sum(&:decisoes_557) %> </td>
                        <td> <%= desempenhos.sum(&:acordos_homologados) %> </td>
                        <td> <%= desempenhos.sum(&:julgamentos_com_merito) %> </td>
                        <td> <%= desempenhos.sum(&:julgamentos_sem_merito) %> </td>
                        <td> <%= desempenhos.sum(&:distribuidos) %> </td>
                        <td> <%= desempenhos.sum(&:redistribuidos) %> </td>
                        <td> <%= desempenhos.sum(&:residuos) %> </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= column_chart @grafico %>
    <% else %>
        <h2>Nenhum Desempenho Nesse Periodo</h2>
    <% end %>
</div>

app/views/desempenhos/edit.html.erb
<h1>Editing Desempenho</h1>

<%= render 'form', desempenho: @desempenho %>

<%= link_to 'Show', @desempenho %>

app/views/desempenhos/index.html.erb
<div class="page-header">
    <h1>Desempenhos do Ano de 2017</h1>
</div>
<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>Mês</th>
            <th>Decisoes</th>
            <th>Decisoes 557</th>
            <th>Acordos</th>
            <th>Julgamentos C/ Mérito</th>
            <th>Julgamentos S/ Mérito</th>
            <th>Distribuidos</th>
            <th>Redistribuidos</th>
            <th>Residuos</th>
        </tr>
    </thead>
    <tbody>
        <% @desempenhos.each do |desempenho| %>
          <tr>
            <td><%= desempenho.data.strftime('%B') %></td>
            <td><%= desempenho.decisoes %></td>
            <td><%= desempenho.decisoes_557 %></td>
            <td><%= desempenho.acordos_homologados %></td>
            <td><%= desempenho.julgamentos_com_merito %></td>
            <td><%= desempenho.julgamentos_sem_merito %></td>
            <td><%= desempenho.distribuidos %></td>
            <td><%= desempenho.redistribuidos %></td>
            <td><%= desempenho.residuos %></td>
          </tr>
        <% end %>
    </tbody>
</table>

<%= column_chart @grafico %>

app/views/desempenhos/listar_desempenhos.html.erb
<div class="page-header">
  <h1>Listar Desempenhos</h1>
</div>

<table id="desempenhos" class="table table-striped table-condensed" width="100%" celspacing="0">
<thead>
    <tr>
      <th></th>
      <th>Orgao</th>
      <th>Magistrado</th>
      <th>Data</th>
      <th>Decisoes</th>
      <th>Decisoes 557</th>
      <th>Acordos</th>
      <th>Julgamentos C/ Mérito</th>
      <th>Julgamentos S/ Mérito</th>
      <th>Distribuidos</th>
      <th>Redistribuidos</th>
      <th>Residuos</th>
    </tr>
  </thead>
  <tbody>
    <% @desempenhos.each do |desempenho| %>
      <tr>
        <td>
          <div class="dropdown show">
            <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Ações
              <span class="caret"></span>
            </button>
            <div class="dropdown-menu">
              <%= link_to('Exibir', desempenho, class: 'dropdown-item btn-block btn btn-sm btn-primary') %>
              <% if current_user %>
                <% if current_user.role === 'admin' %>
                  <% if desempenho.ativo? %>
                  <%= button_to('Desbloquear', desbloquear_path(desempenho), :method => :post, class: 'dropdown-item btn-block btn btn-sm btn-success', remote: true) %>
                  <% else %>
                    <%= button_to('Bloquear', bloquear_path(desempenho), :method => :post, class: 'dropdown-item btn-block btn btn-sm btn-danger', remote: true) %>
                  <% end %>
                <% end %>
                <% if desempenho.ativo? %>
                  <%= link_to("Editar", edit_desempenho_path(desempenho), class: "dropdown-item btn-block btn btn-sm btn-warning", remote: true) %>
                <% end %>
              <% end %>
            </div>
          </div>
        </td>
        <td><%= desempenho.orgao.name %></td>
        <td><%= desempenho.magistrado.name %></td>
        <td><%= desempenho.data.strftime('%B/%Y') %></td>
        <td><%= desempenho.decisoes %></td>
        <td><%= desempenho.decisoes_557 %></td>
        <td><%= desempenho.acordos_homologados %></td>
        <td><%= desempenho.julgamentos_com_merito %></td>
        <td><%= desempenho.julgamentos_sem_merito %></td>
        <td><%= desempenho.distribuidos %></td>
        <td><%= desempenho.redistribuidos %></td>
        <td><%= desempenho.residuos %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Desempenho %>
  <%= link_to '+ Desempenho', new_desempenho_path, class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/desempenhos/new.html.erb
<h1>New Desempenho</h1>

<%= render 'form', desempenho: @desempenho %>

app/views/desempenhos/show.html.erb
<p>
  <strong>Autor:</strong>
  <%= @desempenho.user.name %>
</p>


<p>
  <strong>Orgao:</strong>
  <%= @desempenho.orgao.name %>
</p>

<p>
  <strong>Magistrado:</strong>
  <%= @desempenho.magistrado.prefixo %> <%= @desempenho.magistrado.name %>
</p>

<p>
  <strong>Decisoes:</strong>
  <%= @desempenho.decisoes %>
</p>

<p>
  <strong>Decisoes 557:</strong>
  <%= @desempenho.decisoes_557 %>
</p>

<p>
  <strong>Acordos homologados:</strong>
  <%= @desempenho.acordos_homologados %>
</p>

<p>
  <strong>Julgamentos com merito:</strong>
  <%= @desempenho.julgamentos_com_merito %>
</p>

<p>
  <strong>Julgamentos sem merito:</strong>
  <%= @desempenho.julgamentos_sem_merito %>
</p>

<p>
  <strong>Distribuidos:</strong>
  <%= @desempenho.distribuidos %>
</p>

<p>
  <strong>Redistribuidos:</strong>
  <%= @desempenho.redistribuidos %>
</p>

<p>
  <strong>Residuos:</strong>
  <%= @desempenho.residuos %>
</p>

<div class="btn-group">
  <%= link_to('Exibir', @desempenho, class: 'btn btn-sm btn-primary') %>
  <% if current_user.role == 'admin' %>
    <% if @desempenho.ativo? %>
      <%= link_to('Desbloquear', desbloquear_path(@desempenho), :method => :post, class: 'btn btn-sm btn-success', remote: true) %>
    <% else %>
      <%= link_to('Bloquear', bloquear_path(@desempenho), :method => :post, class: 'btn btn-sm btn-danger' ,remote: true) %>
    <% end %>
    <% else %>
      <% if @desempenho.ativo? %>
        <%= link_to("Editar", edit_desempenho_path(@desempenho), class: "btn btn-warning btn-sm", remote: true) %>
      <% end %>
  <% end %>
</div>