config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :users, :controller => "users"
  resources :desempenhos
  resources :orgaos
  resources :magistrados
  resources :desembargadores

  get 'desempenho_vazio' => 'desempenhos#desempenho_vazio'
  get 'listar_desempenhos' => 'desempenhos#listar_desempenhos'
  get 'desempenhos_magistrados' => 'desempenhos#desempenhos_magistrados'
  get 'desempenhos_orgaos' => 'desempenhos#desempenhos_orgaos'
  post 'gerar_desempenho' => 'desempenhos#gerar_desempenho'
  post 'bloquear/:id' => 'desempenhos#bloquear', as: 'bloquear'
  post 'desbloquear/:id' => 'desempenhos#desbloquear', as: 'desbloquear'
  root to: 'desempenhos#index'

end








app/models/orgao.rb
class Orgao < ApplicationRecord
    has_and_belongs_to_many :magistrados
    has_and_belongs_to_many :users
    has_many :desempenhos
end

app/controllers/orgaos_controller.rb
class OrgaosController < ApplicationController
  load_and_authorize_resource
  before_action :set_orgao, only: [:show, :edit, :update, :destroy]

  # GET /orgaos
  def index
    @orgaos = Orgao.all
  end

  # GET /orgaos/new
  def new
    @orgao = Orgao.new
  end

  # GET /orgaos/:id/edit
  def edit
  end

  # POST /orgaos
  def create
    @orgao = Orgao.new(orgao_params)
    if @orgao.save
      redirect_to @orgao, notice: 'Orgao criado com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /orgaos/:id
  def update
    if @orgao.update(orgao_params)
      redirect_to @orgao, notice: 'Orgao editado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /orgaos/:id
  def destroy
    @orgao.destroy
      redirect_to orgaos_url, notice: 'Orgao deletado com sucesso.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orgao
      @orgao = Orgao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orgao_params
      params.require(:orgao).permit(:name)
    end
end

app/helpers/orgaos_helper.rb
module OrgaosHelper
end

app/views/orgaos/_form.html.erb
<%= simple_form_for(@orgao) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orgaos/edit.html.erb
<h1>Editing Orgao</h1>

<%= render 'form', orgao: @orgao %>

app/views/orgaos/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Orgaos</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @orgaos.each do |orgao| %>
        <tr>
          <td><%= orgao.name %></td>
          <% if can? [:edit, :destroy], Orgao%>
            <td>
              <span class="btn-group" role="group">
                <%= link_to 'Editar', edit_orgao_path(orgao), class:'btn btn-sm btn-warning' %>
                <%= link_to 'Excluir', orgao, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-sm btn-danger' %>
              </span>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if can? :create, Orgao %>
    <%= link_to '+Adicionar Orgão', new_orgao_path, class:'btn btn-sm btn-primary' %>
  <% end %>
</div>

app/views/orgaos/new.html.erb
<h1>New Orgao</h1>

<%= render 'form', orgao: @orgao %>