config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :users, :controller => "users"
  resources :desempenhos
  resources :orgaos
  resources :magistrados
  resources :desembargadores

  get 'desempenho_vazio' => 'desempenhos#desempenho_vazio'
  get 'listar_desempenhos' => 'desempenhos#listar_desempenhos'
  get 'desempenhos_magistrados' => 'desempenhos#desempenhos_magistrados'
  get 'desempenhos_orgaos' => 'desempenhos#desempenhos_orgaos'
  post 'gerar_desempenho' => 'desempenhos#gerar_desempenho'
  post 'bloquear/:id' => 'desempenhos#bloquear', as: 'bloquear'
  post 'desbloquear/:id' => 'desempenhos#desbloquear', as: 'desbloquear'
  root to: 'desempenhos#index'

end








app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jusplan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= javascript_include_tag(:rconsole) if Rails.env.development? %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <%= link_to 'Jusplan', root_path, class: 'navbar-brand' %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Desempenhos
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
              <% if current_user %>
                <% if current_user.admin? %>
                  <li><%= link_to 'Gerar Desempenho', desempenho_vazio_path %></li>
                <% end %>
                <li><%= link_to 'Desempenhos', desempenhos_path %></li>
                <li><%= link_to 'Desempenhos por Magistrado', desempenhos_magistrados_path %></li>
                <li><%= link_to 'Desempenhos por Orgão', desempenhos_orgaos_path %></li>
              <% end %>
                <li><%= link_to 'Desempenho Anual', desempenhos_path %></li>
                <li><%= link_to 'Listar Desempenhos', listar_desempenhos_path %></li>
              </ul>
            </li>
            <li><%= link_to 'Magistrados', magistrados_path %></li>
            <li><%= link_to 'Orgãos', orgaos_path %></li>
            <% if can? :read, User %>
              <li><%= link_to 'Usuários', users_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  Olá <%= current_user.username %> <!--<span class="caret"></span>-->
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Logout', logout_path %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Login', login_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container-fluid">
      <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
      <%= yield %>
    </div>
  <%= console if Rails.env.development? %>
  </body>
</html>